### ISSUE TITLE
How this tool works？

### ISSUE THREAD

**Issue by limoonfeat** [Cuyler36/HorizonCrypt#1]
I backup my save by JKSV，than copy the folder to my PC and put HorizonCrypt within。
like this
\2020.03.21 @ 17.55.21
-Villager0
-main.dat
-mainHeader.dat
-HorizonCrypt.exe

I'm a rookie so what's next??

**Comment by Cuyler36** [comment]
You need to use a command line tool on windows to use it. See usage:
https://github.com/Cuyler36/HorizonCrypt#examples

Your setup you would open a command prompt console and set the current directory to where you have those files then type:
HorizonCrypt -b -d ./

**Comment by limoonfeat** [comment]
HorizonCrypt -d ./J:\Game\NintendoSwitch\Animal Crossing  New Horizons\2020.03.21 @ 17.55.21\main.dat
I click the exe then drag the main.dat into it removed the "" ,but nonthing happen...

**Comment by Cuyler36** [comment]
![image](https://user-images.githubusercontent.com/24523422/77241177-0aac1300-6bc5-11ea-9278-8360075fa430.png)

**Comment by limoonfeat** [comment]
Oh thank you！
