### ISSUE TITLE
Still Doesn't Do Anything

### ISSUE THREAD

**Issue by 77ofspades** [Cuyler36/HorizonCrypt#3]
I think your readme wasnt informative enough. I've ran the programe through cmd and it says Done! However, I didn't get a decrypted file or folder. The file I was trying to decrpyt was named: 800000000000 and 8000000000124. Am I supposed to homebrew my switch or something?

**Comment by Cuyler36** [comment]
Yes you're supposed to use JKSV to dump the save file from Dev Sv. If you're using SXOS there's no user friendly way to dump saves.

**Comment by 77ofspades** [comment]
So yes, I need homebrew. Ya know, this would all be helpful information to include in the readme and not digging deep into reddit
